_INSTITUICOES = sorted([
    # ── Autodidata / Online ──────────────────────────────────
    "Autodidata",
    "Alura",
    "Coursera",
    "DIO (Digital Innovation One)",
    "edX",
    "Fundação Bradesco (Escola Virtual)",
    "Google Ateliê Digital",
    "LinkedIn Learning",
    "Origamid",
    "Rocketseat",
    "FIAP Online",
    "Trybe",
    "Udemy",

    # ── Serviços de Aprendizagem ─────────────────────────────
    "SEBRAE",
    "SENAC",
    "SENAI",
    "SENAR",
    "SESC",
    "SEST SENAT",

    # ── Universidades Federais ───────────────────────────────
    "Universidade de Brasília (UnB)",
    "Universidade Federal da Bahia (UFBA)",
    "Universidade Federal da Fronteira Sul (UFFS)",
    "Universidade Federal da Integração Latino-Americana (UNILA)",
    "Universidade Federal da Paraíba (UFPB)",
    "Universidade Federal de Alagoas (UFAL)",
    "Universidade Federal de Alfenas (UNIFAL-MG)",
    "Universidade Federal de Campina Grande (UFCG)",
    "Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA)",
    "Universidade Federal de Goiás (UFG)",
    "Universidade Federal de Itajubá (UNIFEI)",
    "Universidade Federal de Juiz de Fora (UFJF)",
    "Universidade Federal de Lavras (UFLA)",
    "Universidade Federal de Minas Gerais (UFMG)",
    "Universidade Federal de Mato Grosso (UFMT)",
    "Universidade Federal de Mato Grosso do Sul (UFMS)",
    "Universidade Federal de Ouro Preto (UFOP)",
    "Universidade Federal de Pelotas (UFPel)",
    "Universidade Federal de Pernambuco (UFPE)",
    "Universidade Federal de Roraima (UFRR)",
    "Universidade Federal de Rondônia (UNIR)",
    "Universidade Federal de Santa Catarina (UFSC)",
    "Universidade Federal de Santa Maria (UFSM)",
    "Universidade Federal de São Carlos (UFSCar)",
    "Universidade Federal de São João del-Rei (UFSJ)",
    "Universidade Federal de São Paulo (UNIFESP)",
    "Universidade Federal de Sergipe (UFS)",
    "Universidade Federal de Uberlândia (UFU)",
    "Universidade Federal de Viçosa (UFV)",
    "Universidade Federal do ABC (UFABC)",
    "Universidade Federal do Acre (UFAC)",
    "Universidade Federal do Amapá (UNIFAP)",
    "Universidade Federal do Amazonas (UFAM)",
    "Universidade Federal do Ceará (UFC)",
    "Universidade Federal do Espírito Santo (UFES)",
    "Universidade Federal do Maranhão (UFMA)",
    "Universidade Federal do Oeste da Bahia (UFOB)",
    "Universidade Federal do Pampa (UNIPAMPA)",
    "Universidade Federal do Pará (UFPA)",
    "Universidade Federal do Paraná (UFPR)",
    "Universidade Federal do Piauí (UFPI)",
    "Universidade Federal do Recôncavo da Bahia (UFRB)",
    "Universidade Federal do Rio de Janeiro (UFRJ)",
    "Universidade Federal do Rio Grande (FURG)",
    "Universidade Federal do Rio Grande do Norte (UFRN)",
    "Universidade Federal do Rio Grande do Sul (UFRGS)",
    "Universidade Federal do Sul da Bahia (UFSB)",
    "Universidade Federal do Tocantins (UFT)",
    "Universidade Federal do Triângulo Mineiro (UFTM)",
    "Universidade Federal dos Vales do Jequitinhonha e Mucuri (UFVJM)",
    "Universidade Federal do Vale do São Francisco (UNIVASF)",
    "Universidade Federal Rural da Amazônia (UFRA)",
    "Universidade Federal Rural de Pernambuco (UFRPE)",
    "Universidade Federal Rural do Rio de Janeiro (UFRRJ)",
    "Universidade Federal Rural do Semiárido (UFERSA)",
    "Universidade Tecnológica Federal do Paraná (UTFPR)",

    # ── Universidades Estaduais ──────────────────────────────
    "Universidade de Caxias do Sul (UCS)",
    "Universidade de Pernambuco (UPE)",
    "Universidade de São Paulo (USP)",
    "Universidade do Estado da Bahia (UNEB)",
    "Universidade do Estado de Santa Catarina (UDESC)",
    "Universidade do Estado do Amazonas (UEA)",
    "Universidade do Estado do Mato Grosso (UNEMAT)",
    "Universidade do Estado do Rio de Janeiro (UERJ)",
    "Universidade do Estado do Rio Grande do Norte (UERN)",
    "Universidade do Oeste de Santa Catarina (UNOESC)",
    "Universidade do Vale do Rio dos Sinos (UNISINOS)",
    "Universidade Estadual de Campinas (UNICAMP)",
    "Universidade Estadual de Feira de Santana (UEFS)",
    "Universidade Estadual de Goiás (UEG)",
    "Universidade Estadual de Londrina (UEL)",
    "Universidade Estadual de Maringá (UEM)",
    "Universidade Estadual de Minas Gerais (UEMG)",
    "Universidade Estadual de Montes Claros (UNIMONTES)",
    "Universidade Estadual de Ponta Grossa (UEPG)",
    "Universidade Estadual do Ceará (UECE)",
    "Universidade Estadual do Maranhão (UEMA)",
    "Universidade Estadual do Norte do Paraná (UENP)",
    "Universidade Estadual do Oeste do Paraná (UNIOESTE)",
    "Universidade Estadual do Paraná (UNESPAR)",
    "Universidade Estadual do Piauí (UESPI)",
    "Universidade Estadual do Rio Grande do Sul (UERGS)",
    "Universidade Estadual Paulista (UNESP)",
    "Universidade Regional de Blumenau (FURB)",

    # ── Institutos Federais ──────────────────────────────────
    "Instituto Federal de Alagoas (IFAL)",
    "Instituto Federal de Goiás (IFG)",
    "Instituto Federal de Minas Gerais (IFMG)",
    "Instituto Federal de Pernambuco (IFPE)",
    "Instituto Federal de Roraima (IFRR)",
    "Instituto Federal de Santa Catarina (IFSC)",
    "Instituto Federal de Sergipe (IFS)",
    "Instituto Federal do Acre (IFAC)",
    "Instituto Federal do Amapá (IFAP)",
    "Instituto Federal do Amazonas (IFAM)",
    "Instituto Federal do Bahia (IFBA)",
    "Instituto Federal do Ceará (IFCE)",
    "Instituto Federal do Espírito Santo (IFES)",
    "Instituto Federal do Maranhão (IFMA)",
    "Instituto Federal do Mato Grosso (IFMT)",
    "Instituto Federal do Mato Grosso do Sul (IFMS)",
    "Instituto Federal do Pará (IFPA)",
    "Instituto Federal do Paraná (IFPR)",
    "Instituto Federal do Piauí (IFPI)",
    "Instituto Federal do Rio de Janeiro (IFRJ)",
    "Instituto Federal do Rio Grande do Norte (IFRN)",
    "Instituto Federal do Rio Grande do Sul (IFRS)",
    "Instituto Federal do Rondônia (IFRO)",
    "Instituto Federal do São Paulo (IFSP)",
    "Instituto Federal do Tocantins (IFTO)",
    "Instituto Federal Catarinense (IFC)",
    "Instituto Federal Farroupilha (IFFar)",
    "Instituto Federal Fluminense (IFF)",
    "Instituto Federal Goiano (IF Goiano)",
    "Instituto Federal Sul-rio-grandense (IFSul)",
    "Instituto Federal do Sul de Minas (IFSULDEMINAS)",
    "Instituto Federal do Triângulo Mineiro (IFTM)",

    # ── Privadas (PUCs) ──────────────────────────────────────
    "Pontifícia Universidade Católica de Campinas (PUC-Campinas)",
    "Pontifícia Universidade Católica de Minas Gerais (PUC Minas)",
    "Pontifícia Universidade Católica de São Paulo (PUC-SP)",
    "Pontifícia Universidade Católica do Paraná (PUCPR)",
    "Pontifícia Universidade Católica do Rio de Janeiro (PUC-Rio)",
    "Pontifícia Universidade Católica do Rio Grande do Sul (PUCRS)",
    "Universidade Católica de Brasília (UCB)",
    "Universidade Católica do Salvador (UCSal)",

    # ── Privadas (Grupos Nacionais) ──────────────────────────
    "Universidade Anhanguera",
    "Centro Universitário Anhanguera",
    "Universidade Cruzeiro do Sul",
    "Universidade Estácio de Sá",
    "Universidade Estácio do Amazonas",
    "Universidade Metodista de São Paulo",
    "Universidade Nove de Julho (UNINOVE)",
    "Universidade Paulista (UNIP)",
    "Universidade Positivo",
    "Universidade Tiradentes (Unit)",
    "Universidade do Grande ABC",
    "Universidade de Fortaleza (UNIFOR)",
    "Universidade Salvador (UNIFACS)",
    "Universidade Tuiuti do Paraná",
    "Universidade Presbiteriana Mackenzie",
    "Faculdade de Tecnologia do Estado do Amazonas (FAMETRO)",

    # ── Privadas (Referência) ────────────────────────────────
    "Centro Universitário FIAP",
    "Centro Universitário Senac",
    "ESPM – Escola Superior de Propaganda e Marketing",
    "Faculdade SENAI",
    "Fundação Getulio Vargas (FGV)",
    "Ibmec",
    "INSPER – Instituto de Ensino e Pesquisa",
])


def buscar(termo: str, limite: int = 10) -> list[str]:
    t = termo.lower()
    return [i for i in _INSTITUICOES if t in i.lower()][:limite]
