_LOCALIDADES = sorted([
    # ── Capitais ─────────────────────────────────────────────
    "Manaus, AM",
    "Belém, PA",
    "Porto Velho, RO",
    "Macapá, AP",
    "Boa Vista, RR",
    "Rio Branco, AC",
    "Palmas, TO",
    "São Luís, MA",
    "Teresina, PI",
    "Fortaleza, CE",
    "Natal, RN",
    "João Pessoa, PB",
    "Recife, PE",
    "Maceió, AL",
    "Aracaju, SE",
    "Salvador, BA",
    "Vitória, ES",
    "Belo Horizonte, MG",
    "Rio de Janeiro, RJ",
    "São Paulo, SP",
    "Curitiba, PR",
    "Florianópolis, SC",
    "Porto Alegre, RS",
    "Campo Grande, MS",
    "Cuiabá, MT",
    "Goiânia, GO",
    "Brasília, DF",

    # ── Cidades grandes / polo ───────────────────────────────
    "Ananindeua, PA",
    "Aparecida de Goiânia, GO",
    "Barueri, SP",
    "Belford Roxo, RJ",
    "Betim, MG",
    "Camaçari, BA",
    "Campina Grande, PB",
    "Campinas, SP",
    "Carapicuíba, SP",
    "Caucaia, CE",
    "Contagem, MG",
    "Diadema, SP",
    "Duque de Caxias, RJ",
    "Feira de Santana, BA",
    "Florianópolis, SC",
    "Fortaleza, CE",
    "Franca, SP",
    "Goiânia, GO",
    "Guarulhos, SP",
    "Itabuna, BA",
    "Jaboatão dos Guararapes, PE",
    "Joinville, SC",
    "Juazeiro do Norte, CE",
    "Juiz de Fora, MG",
    "Londrina, PR",
    "Macaé, RJ",
    "Manaus, AM",
    "Marabá, PA",
    "Maringá, PR",
    "Mauá, SP",
    "Mossoró, RN",
    "Niterói, RJ",
    "Nova Iguaçu, RJ",
    "Olinda, PE",
    "Osasco, SP",
    "Pelotas, RS",
    "Petrolina, PE",
    "Ribeirão Preto, SP",
    "Rio Branco, AC",
    "Santo André, SP",
    "Santos, SP",
    "São Bernardo do Campo, SP",
    "São Gonçalo, RJ",
    "São José do Rio Preto, SP",
    "São José dos Campos, SP",
    "São Luís, MA",
    "Serra, ES",
    "Sorocaba, SP",
    "Teresina, PI",
    "Uberlândia, MG",
    "Vila Velha, ES",

    # ── Cidades do AM ────────────────────────────────────────
    "Coari, AM",
    "Itacoatiara, AM",
    "Parintins, AM",
    "Tabatinga, AM",
    "Tefé, AM",

    # ── Exterior ─────────────────────────────────────────────
    "EAD / Online",
    "Remoto",
    "Lisboa, Portugal",
    "Porto, Portugal",
    "Miami, EUA",
    "New York, EUA",
    "Toronto, Canadá",
    "Dublin, Irlanda",
])


def buscar(termo: str, limite: int = 8) -> list[str]:
    t = termo.lower()
    return [l for l in _LOCALIDADES if t in l.lower()][:limite]
